spring.application.name=EnergySharingHub
# Database URL (energy_sharing_hub wahi naam hai jo step 1 mein rakha)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/energy_sharing_hub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password= root

# Hibernate logic: Isse tables automatic ban jayenge
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080